name: hecta
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.1.3+467

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  built_collection: 5.1.1
  built_value: 8.4.0
  cached_network_image: 3.2.1
  chewie: 1.3.4
  cloud_firestore: 4.2.0
  cloud_firestore_platform_interface: 5.9.1
  cloud_firestore_web: 3.1.1
  cloud_functions: 4.0.6
  cloud_functions_platform_interface: 5.1.25
  cloud_functions_web: 4.3.14
  csv: 5.0.1
  easy_debounce: 2.0.1
  equatable: 2.0.3
  expandable: 5.0.1
  file_picker: ^4.6.1
  firebase_analytics: 10.0.7
  firebase_analytics_platform_interface: 3.3.15
  firebase_analytics_web: 0.5.1+6
  firebase_auth: 4.2.0
  firebase_auth_platform_interface: 6.11.4
  firebase_auth_web: 5.2.0
  firebase_core: 2.4.0
  firebase_core_platform_interface: 4.5.2
  firebase_core_web: 2.0.2
  firebase_crashlytics: 3.0.7
  firebase_crashlytics_platform_interface: 3.3.8
  firebase_messaging: 14.1.4
  firebase_messaging_platform_interface: 4.2.8
  firebase_messaging_web: 3.2.9
  firebase_remote_config: 3.0.7
  firebase_storage: 11.0.7
  firebase_storage_platform_interface: 4.1.25
  firebase_storage_web: 3.3.17
  flutter_animate: 1.0.0
  flutter_cache_manager: 3.3.0
  flutter_facebook_auth: 
    git:
      url: https://github.com/asmengistu/flutter-facebook-auth
      ref: b65ffb049c9f1e2704adbeb1aa19c61693c946a5
      path: facebook_auth
  flutter_html: 3.0.0-alpha.5
  flutter_rating_bar: 4.0.1
  flutter_secure_storage: 6.0.0
  flutter_spinkit: 5.1.0
  flutter_stripe: 4.0.0
  flutter_stripe_web: 1.2.0
  flutter_svg: 0.22.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  geolocator: 9.0.1
  geolocator_android: 4.1.0
  geolocator_apple: 2.2.1
  geolocator_platform_interface: 4.0.6
  geolocator_web: 2.1.6
  go_router: 3.1.0
  google_fonts: 3.0.1
  google_maps: 6.2.0
  google_maps_flutter: 2.1.8
  google_maps_flutter_platform_interface: 2.2.1
  google_maps_flutter_web: 0.4.0+1
  google_sign_in: 5.4.0
  google_sign_in_ios: 5.4.0
  google_sign_in_platform_interface: 2.2.0
  google_sign_in_web: 0.10.2
  image_picker: 0.8.5+3
  image_picker_android: 0.8.5+3
  image_picker_for_web: 2.1.10
  image_picker_ios: 0.8.6+1
  image_picker_platform_interface: 2.6.2
  infinite_scroll_pagination: 3.2.0
  intl: 0.17.0
  json_path: 0.4.1
  json_serializable: 6.3.1
  list_tile_switch: ^1.0.0
  map_launcher: 2.2.3
  mapbox_search: 3.0.1+2
  mime_type: 1.0.0
  page_transition: 2.0.4
  pdf: ^3.8.1
  photo_view: 0.14.0
  pin_code_fields: 7.4.0
  plugin_platform_interface: 2.1.3
  printing: ^5.9.1
  provider: 6.0.4
  rxdart: 0.27.4
  share_plus: 2.1.4
  shared_preferences: 2.0.15
  sign_in_with_apple: 4.1.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  smooth_page_indicator: 1.0.0+2
  sqflite: 2.2.0+2
  stripe_android: 4.0.0
  stripe_ios: 4.0.0
  stripe_platform_interface: 4.0.0
  substring_highlight: 1.0.33
  syncfusion_flutter_sliders: ^20.3.52
  timeago: 3.2.2
  url_launcher: 6.1.5
  video_player: 2.4.5
  video_player_android: 2.3.8
  video_player_avfoundation: 2.3.5
  video_player_platform_interface: 5.1.3
  video_player_web: 2.0.12
  webviewx_plus: 
    git:
      url: https://github.com/FlutterFlow/webviewx_plus.git


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
  provider: 6.0.0
  webview_flutter_android: 2.10.3
  webview_flutter_platform_interface: 1.9.5
  webview_flutter_wkwebview: 2.9.5

dev_dependencies:
  build_runner: 2.2.0
  built_value_generator: 8.4.0
  flutter_launcher_icons: 0.9.3

  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/app_launcher_icon.jpg'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

  fonts:
    - family: Kolkata
      fonts:
        - asset: assets/fonts/kolkata.ttf
    - family: Noida
      fonts:
        - asset: assets/fonts/noida.ttf
    - family: Mumbai
      fonts:
        - asset: assets/fonts/mumbai.ttf
    - family: Hyderabad
      fonts:
        - asset: assets/fonts/hyderabad.ttf
    - family: Chennai
      fonts:
        - asset: assets/fonts/chennai.ttf
    - family: Delhi
      fonts:
        - asset: assets/fonts/delhi.ttf
    - family: GrNoida
      fonts:
        - asset: assets/fonts/gr-noida.ttf
    - family: Pune
      fonts:
        - asset: assets/fonts/pune.ttf
    - family: Bangalore
      fonts:
        - asset: assets/fonts/bangalore.ttf
    - family: Gurgaon
      fonts:
        - asset: assets/fonts/gurgaon.ttf
    - family: Shop
      fonts:
        - asset: assets/fonts/shop.ttf
    - family: ResPlot
      fonts:
        - asset: assets/fonts/res_plot.ttf
    - family: ResidFlat
      fonts:
        - asset: assets/fonts/resid_flat.ttf
    - family: IndepHouse
      fonts:
        - asset: assets/fonts/indep_house.ttf
    - family: CommOff
      fonts:
        - asset: assets/fonts/comm_off.ttf
    - family: IndusPlot
      fonts:
        - asset: assets/fonts/indus_plot.ttf
    - family: Warehouse
      fonts:
        - asset: assets/fonts/warehouse.ttf
    - family: Icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
    - family: ChennaiF
      fonts:
        - asset: assets/fonts/Chennai_F.ttf
    - family: AgriLand
      fonts:
        - asset: assets/fonts/agri_land.ttf
    - family: Bang
      fonts:
        - asset: assets/fonts/bang.ttf
    - family: PreferencesInactive
      fonts:
        - asset: assets/fonts/preferences-inactive.ttf
    - family: PreferencesActive
      fonts:
        - asset: assets/fonts/preferences-active.ttf
    - family: HectaBulletIcon
      fonts:
        - asset: assets/fonts/hecta-bulletIcon.ttf
    - family: Filters
      fonts:
        - asset: assets/fonts/filters.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
